In [969]:
import numpy as np

power = 6
population = 6  # even
generation = 15  # total number of evaluations
mutation_ratio = 0.1  # possibility for each 1/0 in mutation, for each geno in mutation2
'''modifiable above'''
min = 0
max = 2**power - 1
geno_len = len(bin(max)[2:])  # length of binary representation
def objFunc(x):
    return x**2

In [970]:
def encoding_vec(array):
    return np.vectorize(np.binary_repr)(array, width=geno_len)

def decoding_vec(array):
    return np.vectorize(int)(array, 2)

# Generate initial population at random in int
geno_list = np.random.randint(min, max, size=(generation, population))
geno_list[1:, :] = 0

geno_list

array([[16, 47, 13, 30, 36,  2],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [971]:
def roulette_wheel(array):
    return objFunc(array)/sum(objFunc(array))

roulette_wheel(geno_list[0, :])

array([0.05295821, 0.45697145, 0.0349607 , 0.18618122, 0.26810095,
       0.00082747])

In [972]:
def get_parents(array):
    return np.random.choice(encoding_vec(array), size=population, p=roulette_wheel(array))

parents = get_parents(geno_list[0, :])
parents

array(['100100', '101111', '101111', '101111', '001101', '101111'],
      dtype='<U6')

In [973]:
def crossover(array):
    descendants = []
    for i in range(0, population, 2):
        rad = np.random.randint(1, geno_len-1)
        descendants.append(array[i][:rad] + array[i+1][rad:])
        descendants.append(array[i+1][:rad] + array[i][rad:])
    return descendants

descendants = crossover(parents)
descendants

['100111', '101100', '101111', '101111', '001111', '101101']

In [974]:
def mutation(array, ratio):
    aftermutation = []
    for geno in array:
        split = [char if np.random.rand() > ratio else str(1 - int(char))
                 for char in geno]
        aftermutation.append("".join(split))
    return aftermutation

descendants_mutation = mutation(descendants, mutation_ratio)
descendants_mutation

['100111', '101100', '011011', '001111', '001111', '101110']

In [975]:
def mutation2(array, ratio):
    aftermutation = []
    for geno in array:
        if np.random.rand() < ratio:
            rad = np.random.randint(geno_len)
            aftermutation.append(
                geno[:rad] + str(1 - int(geno[rad])) + geno[rad+1:])
        else:
            aftermutation.append(geno)
    return aftermutation


descendants_mutation = mutation2(descendants, mutation_ratio)
descendants_mutation


['100111', '101100', '101111', '101111', '001111', '101101']

In [976]:
# training
for i in range(generation-1):
    parents = get_parents(geno_list[i, :])
    descendants = crossover(parents)
    descendants_mutation = mutation(descendants, mutation_ratio)
    # descendants_mutation = mutation2(descendants, mutation_ratio)
    geno_list[i+1, :] = decoding_vec(descendants_mutation)

print(geno_list)

[[16 47 13 30 36  2]
 [45 55 16 44 62 11]
 [44 37 45 55 62 55]
 [54 59 38 61 63 39]
 [54 31 27 55 63 61]
 [39 61 55 44 62 55]
 [62 62 63 62 60 45]
 [60 61 63 46 63 28]
 [29 60 63 59 61 46]
 [61 61 61 27 59 63]
 [58 47 47 57 63 45]
 [48 57 15 46 59 30]
 [14 24 59 63 62 25]
 [59 62 62 59 41 30]
 [46 59 50 63 62 59]]
